### ISSUE TITLE
CSS Modules className not applied on development

### ISSUE THREAD

**Issue by vasilenka** [devloco/create-react-wptheme#27] opened 2019-09-27 10:42 UTC
CSS Modules not working for module.scss and module.css files.

The className being generated, but not attached to the HTML.

This is the CSS file being generated

<img width="252" alt="Screen Shot 2019-09-27 at 17 39 35" src="https://user-images.githubusercontent.com/7563139/65763547-de4f9680-e14d-11e9-8fa2-e82adb92b6bc.png">

The className should be applied to `<p>` tag, but there's not className applied.

<img width="261" alt="Screen Shot 2019-09-27 at 17 39 19" src="https://user-images.githubusercontent.com/7563139/65763671-2078d800-e14e-11e9-8674-d56b63c19c9f.png">

It's not working in development, the production build working just fine.

**Comment by devloco** [comment] 2019-09-27 17:15
I'll fix it up this weekend. Thanks for letting me know!

**Comment by devloco** [comment] 2019-09-28 23:09
I think this is fixed now. I'm not a CSS or CSS Module expert, so I used an article from the WWW to help me come up with some test scenarios:

[How to use Sass and CSS Modules with create-react-app](https://blog.bitsrc.io/how-to-use-sass-and-css-modules-with-create-react-app-83fa8b805e5e)

When I rename `App.css` to `App.module.css` and rename all the selectors to replace dashes with underscores, it all seems to work.

However if I renamed `App.css` to `Module.css` then it looks broken. So it looks like you need some kind of file name prefix for CSS Modules...?

Anyway, let me know if this isn't what you expected, and, in that case, also some steps to reproduce the issue.

Thanks!

**Comment by devloco** [comment] 2019-09-28 23:13
----
Obligatory link to the updating instructions:
https://github.com/devloco/create-react-wptheme#updating-existing-themes
----

**Comment by vasilenka** [comment] 2019-09-29 02:05
Thank you so much! It's working properly now.

Yeah, you need the stylesheet name to be `*.module.*` to use it on `create-react-app` because that's how they do the setup on `react-scripts` webpack config.

https://github.com/devloco/create-react-wptheme-scripts/blob/55b8f14a79ea0913ac1fc95a6c7e1bc0f813f573/packages/react-scripts/config/webpack.config.js#L57-L61

**Closed as completed** 2019-09-29 02:06 UTC
Labels: bug
