### ISSUE TITLE
Freezing everything on windows 10

### ISSUE THREAD

**Issue by karanmandal** [devloco/create-react-wptheme#50] opened 2020-04-16 06:44 UTC
File-watcher is consuming too much disk also freezing everything, I tried by configuring, interval and binary Interval to 2000, but still, it starts hanging after some time.

**user.dev.json**
```json
{
	 "fileWatcherPlugin": {
		  "touchFile": "./public/index.php",
		  "ignored": "./public/index.php",
		  "watchFileGlobs": [
			   "./public/**/*.js",
			   "./public/**/*.css",
			   "./public/**/*.php"
		  ],
		  "interval": 2000,
		  "binaryInterval": 2000
	 },
	 "wpThemeServer": {
		  "enable": true,
		  "host": "127.0.0.1",
		  "port": 8090,
		  "sslCert": null,
		  "sslKey": null
	 },
	 "injectWpThemeClient": {
		  "override": null,
		  "file": "./build/index.php"
	 }
}
```

**Comment by devloco** [comment] 2020-04-16 18:10
@karanmandal,

**Yikes!** Can you provide any more details?

- Basically how can I reproduce this on my machine?
- Is this just a bare brand new theme that you're testing, or have you added any other NPMs to your project?
- Etc...?

Thanks for reporting the bug and my apologies for the hassle.

**Comment by devloco** [comment] 2020-04-16 18:25
@karanmandal,

I just realized that you put "Windows 10" in the Subject. Thanks.

**Comment by devloco** [comment] 2020-04-17 00:50
Hi @karanmandal,

I just published a new version of the `utils` package. All it does is set polling to "false" by default. According to the [chokidar README](https://github.com/paulmillr/chokidar), that can cause "high CPU utilization."

If that doesn't help you out, you should look at these chokidar options:
- depth
- awaitWriteFinish
- atomic

Also, I wasn't able to reproduce this on my dev machine. If you provide enough details on your setup, then I can try again. I don't mind abandoning `chokidar` for something else. But I'd need to be able to test it all myself.

I hope that helps. Good luck!

**Comment by devloco** [comment] 2020-04-24 20:44
Hi @karanmandal,

Since I was unable to reproduce this and so much time has gone by, I am going to close this.
If you're able to instruct me to create a reproducible scenario, then feel free to reopen it. And I'll take a look then.

Thanks.

**Closed as completed by devloco** 2020-04-24 20:44 UTC
Labels: not reproducible, not enough info
